spring:
  application:
    name: flowroad-backend

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB
  
  # (Capa de Infraestructura)
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/flowroad_db}

# Configuración del servidor embebido
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api/v1 

# (Capa General)
jwt:
  secret: ${JWT_SECRET_KEY:clave_de_desarrollo_super_larga_y_segura_solo_local_987654321_usar_mas_de_256_bits}
  expiration: 86400000

# Firebase Cloud Messaging
firebase:
  enabled: ${FIREBASE_ENABLED:false}
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH:}

aws:
  region: ${AWS_REGION:}
  s3:
    bucket: ${AWS_S3_BUCKET:}

onlyoffice:
  document-server-url: ${ONLYOFFICE_DOCUMENT_SERVER_URL:http://localhost:8082}
  jwt-secret: ${ONLYOFFICE_JWT_SECRET:flowroad_onlyoffice_secret}
  callback-base-url: ${ONLYOFFICE_CALLBACK_BASE_URL:http://host.docker.internal:8080/api/v1}
